name: Kind 2 DockerHub

on:
  push:
    branches: [ master, develop ]

jobs:
  build-and-publish:
    if: github.repository == 'kind2-mc/kind2'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      run: |
        image=kind2/kind2
        tag=${{ github.ref == 'refs/heads/master' && 'latest' || 'dev' }}
        echo "tag=$image:$tag" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        file: docker/Dockerfile
        tags: ${{ steps.meta.outputs.tag }}
    
    # Disabled because Docker Hub Personal Access Tokens are not currently accepted.
    # See:
    #   https://github.com/docker/hub-feedback/issues/1927
    #   https://github.com/docker/hub-feedback/issues/1914
    # Future support can be monitored here:
    #   https://github.com/docker/roadmap/issues/115
    #- name: Update repo description
    #  uses: peter-evans/dockerhub-description@v2
    #  with:
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
    #    repository: ${{ steps.meta.outputs.image }}
    #    readme-filepath: ./docker/README.md
